---
# Setup active directory membership

- block:
    # Create computer account to ensure long name is used
    - include_tasks: computer.yml
    - include_tasks: wait.yml

    # Join to the realm
    - include_tasks: join.yml
  tags:
    - role::linux_ad_auth
