---

- name: Setup authconfig
  block:
    - name: Configure autentication
      ansible.builtin.command: >-
        /usr/sbin/authconfig
        --enablesssd
        --enablesssdauth
        --enablekrb5
        --enablelocauthorize
        --enablemkhomedir
        --update
      changed_when: yes

    - name: Setup kerberos config file
      ansible.builtin.template:
        src: krb5.conf.j2
        dest: /etc/krb5.conf
        owner: root
        group: root
        mode: 0644
        backup: yes
  tags:
    - role::linux_ad_auth
