---
# Main role tasks

- block:
    - name: Configure autentication
      command: >-
        /usr/sbin/authconfig
        --enablesssd
        --enablesssdauth
        --enablekrb5
        --enablelocauthorize
        --enablemkhomedir
        --update

    - name: Setup kerberos config file
      template:
        src: krb5.conf.j2
        dest: /etc/krb5.conf
        owner: root
        group: root
        mode: 0644
        backup: yes
  tags:
    - role::linux_ad_auth
