---

- name: Setup authselect
  block:
    - name: Configure autentication
      ansible.builtin.command: >-
        /usr/bin/authselect select sssd with-mkhomedir --force
      changed_when: yes
  tags:
    - role::linux_ad_auth
