---
# Join host to realm

- block:
    - name: Join host to domain
      expect:
        command: >-
          /usr/sbin/realm join '{{ linux_ad_auth_krb5_realm }}'
          --user='{{ linux_ad_auth_user }}'
          --computer-ou='{{ linux_ad_auth_host_ou }}'
          --computer-name='{{ linux_ad_auth_host_netbios_name }}'
          --os-name='{{ linux_ad_auth_distro_version_result.stdout.1 }}'
          --os-version='{{ linux_ad_auth_distro_version_result.stdout.0 }}'
          --verbose
        responses:
          ":": "{{ linux_ad_auth_password }}"
      register: linux_ad_auth_join_realm_result
      failed_when: >-
        linux_ad_auth_join_realm_result.rc != 0
        and "realm: Already joined to this domain"
            not in linux_ad_auth_join_realm_result.stdout
      until: linux_ad_auth_join_realm_result is success
      retries: "{{ linux_ad_retries }}"
      delay: "{{ linux_ad_delay }}"
  environment:
    LC_ALL: en_US.UTF-8
    LC_CTYPE: en_US.UTF-8
  tags:
    - role::linux_ad_auth
