---

- name: Leave domain
  ansible.builtin.command: /usr/sbin/realm leave -v
  register: linux_ad_auth_leave_realm_result
  changed_when: yes
  failed_when: >
    linux_ad_auth_leave_realm_result.rc != 0
    and "realm: Couldn't find a configured realm"
        not in linux_ad_auth_join_realm_result.stdout
  when: linux_ad_auth_state == "absent"
  until: linux_ad_auth_leave_realm_result is success
  retries: "{{ linux_ad_retries }}"
  delay: "{{ linux_ad_delay }}"
  environment:
    LC_ALL: en_US.UTF-8
    LC_CTYPE: en_US.UTF-8
  tags:
    - role::linux_ad_auth

- name: Setup computer account
  include_tasks: computer.yml

- name: Wait for computer account
  include_tasks: wait.yml
