---
# Leave realm

- name: Leave domain
  command: /usr/sbin/realm leave -v
  register: linux_ad_auth_leave_realm_result
  failed_when: >
    linux_ad_auth_leave_realm_result.rc != 0
    and "realm: Couldn't find a configured realm"
        not in linux_ad_auth_join_realm_result.stdout
  environment:
    LC_ALL: en_US.UTF-8
    LC_CTYPE: en_US.UTF-8
  tags:
    - role::linux_ad_auth
