---
# Main role tasks

- block:
    - include_tasks: check.yml
    - block:
        - block:
            - include_tasks: gather.yml

            - include_tasks: authconfig.yml
              when: >-
                linux_ad_auth_distro_version_result.stdout.0
                is version("8", "<")

            - include_tasks: authselect.yml
              when: >-
                linux_ad_auth_distro_version_result.stdout.0
                is version("8", ">=")

            - include_tasks: ad.yml
            - include_tasks: sssd.yml
          when: linux_ad_auth_state == "present"
          vars:
            linux_ad_auth_ad_hostname: "{{ inventory_hostname }}"

        - include_tasks: leave.yml
          when: linux_ad_auth_state == "absent"

        - include_tasks: services.yml
      when: >-
        ("configured: no" in ssd_realm_discover_result.stdout
          and linux_ad_auth_state == "present")
        or ("configured: kerberos-member" in ssd_realm_discover_result.stdout
             and linux_ad_auth_state == "absent")
  tags:
    - role::linux_ad_auth
