---
# Main role tasks

- block:
    - include_tasks: check.yml
    - block:
        - block:
            # This is a workaround to avoid dependency on ansible facts to
            # configure authentication
            - name: Gather distribution version
              command: >-
                {{ ansible_python_interpreter
                   | default("python") }}
                -c "{{ linux_ad_auth_gather_distro_script }}"
              register: linux_ad_auth_distro_version_result
              changed_when: no
              vars:
                linux_ad_auth_gather_distro_script: >-
                  try:
                    import distro
                    print(distro.version())
                    print(distro.name())
                  except:
                    import platform;
                    print(platform.linux_distribution()[1])
                    print(platform.linux_distribution()[0].split(' ')[0])

            - include_tasks: authconfig.yml
              when: >-
                linux_ad_auth_distro_version_result.stdout.0
                is version("8", "<")

            - include_tasks: authselect.yml
              when: >-
                linux_ad_auth_distro_version_result.stdout.0
                is version("8", ">=")

            - include_tasks: ad.yml
            - include_tasks: sssd.yml
          when: linux_ad_auth_state == "present"
          vars:
            linux_ad_auth_ad_hostname: "{{ inventory_hostname }}"

        - include_tasks: leave.yml
          when: linux_ad_auth_state == "absent"

        - include_tasks: services.yml
      when: >-
        ("configured: no" in ssd_realm_discover_result.stdout
          and linux_ad_auth_state == "present")
        or ("configured: kerberos-member" in ssd_realm_discover_result.stdout
             and linux_ad_auth_state == "absent")
  tags:
    - role::linux_ad_auth
