---
# Main role tasks

- name: Setup linux active directory authentication
  block:
    - name: Check authentication status
      include_tasks: check.yml

    - name: Perform active directory authentication configuration
      block:
        - name: Add active directory authentication
          block:
            - name: Gather authentication info
              include_tasks: gather.yml

            - name: Setup authconfig
              include_tasks: authconfig.yml
              when: >-
                linux_ad_auth_distro_version_result.stdout_lines.0
                is version("8", "<")

            - name: Setup authselect
              include_tasks: authselect.yml
              when: >-
                linux_ad_auth_distro_version_result.stdout_lines.0
                is version("8", ">=")

            - name: Setup active directory stuff
              include_tasks: ad.yml

            - name: Setup sssd
              include_tasks: sssd.yml
          when: linux_ad_auth_state == "present"
          vars:
            linux_ad_auth_ad_hostname: "{{ inventory_hostname }}"

        - name: Remove active directory authentication
          include_tasks: leave.yml
          when: linux_ad_auth_state == "absent"

        - name: Setup authentication services
          include_tasks: services.yml
      when: >-
        ("configured: no" in ssd_realm_discover_result.stdout
          and linux_ad_auth_state == "present")
        or ("configured: kerberos-member" in ssd_realm_discover_result.stdout
             and linux_ad_auth_state == "absent")
  tags:
    - role::linux_ad_auth
