---

- name: Cleanup
  hosts: molecule_hosts
  become: yes
  tasks:
    - name: Cleanup
      ansible.builtin.include_role:
        name: amtega.linux_ad_auth
      vars:
        linux_ad_auth_state: absent
