---

- name: Cleanup
  hosts: "{{ linux_ad_auth_tests_host }}"
  tasks:
    - include_tasks: check_paremeters.yml

    - name: Cleanup
      include_role:
        name: amtega.linux_ad_auth
      vars:
        linux_ad_auth_state: absent
  vars:
    linux_ad_auth_domain: "{{ linux_ad_auth_tests_domain }}"
    linux_ad_auth_host_netbios_name: >-
      {{ linux_ad_auth_tests_host_netbios_name }}
    linux_ad_auth_sssd_simple_allow_groups:
      - "{{ linux_ad_auth_tests_sssd_simple_allow_groups }}"
    linux_ad_auth_host_ou: >-
      {{ linux_ad_auth_tests_host_ou }}
    linux_ad_auth_user: "{{ linux_ad_auth_tests_user }}"
    linux_ad_auth_password: "{{ linux_ad_auth_tests_password }}"
    linux_ad_auth_intermediate: "{{ linux_ad_auth_tests_intermediate }}"
