---

- name: Converge
  hosts: molecule_hosts
  become: yes
  tasks:
    - name: Test linux_ad_auth role
      ansible.builtin.include_role:
        name: amtega.linux_ad_auth
      vars:
        linux_ad_auth_state: present
